export const configs = {
  Square: {
    rows: 14,
    cols: 14,
    button: 39,
    data: 32,
    clock: 26,
    milliamps: 4000,
    chipType: "atom",
    ledType: "SK9822",
    serpentine: true,
  },
  Tapestry: {
    rows: 70,
    cols: 15,
    button: 39,
    data: 32,
    clock: 26,
    milliamps: 7000,
    chipType: "atom",
    ledType: "SK9822",
    serpentine: true,
  },
  Mini: {
    rows: 5,
    cols: 5,
    button: 39,
    data: 27,
    clock: 26,
    milliamps: 200,
    chipType: "atom",
    ledType: "WS2812B",
    serpentine: false,
  },
};
